os:
- linux
language: rust
rust: 
    - stable
    - beta
    - nightly
allow_failures:
    - rust: nightly
after_success: 'curl https://raw.githubusercontent.com/iron-bot/build-doc/master/build-doc.sh
  | sh '
