[package]

name = "urlencoded"
authors = ["Patrick Tran <patrick.tran06@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"

[[lib]]

name = "urlencoded"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

